version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    open-pull-requests-limit: 5
    schedule:
      interval: 'weekly'
      time: '12:00'
      day: 'sunday'
      timezone: 'America/Los_Angeles'
  - package-ecosystem: 'npm'
    directory: '/'
    open-pull-requests-limit: 5
    schedule:
      interval: 'weekly'
      time: '12:00'
      day: 'sunday'
      timezone: 'America/Los_Angeles'
    groups:
      dev-deps:
        dependency-type: 'development'
      patch-dependencies:
        update-types:
          - 'patch'