name: Node CI Suite

on: push

jobs:
  test:
    runs-on: ${{ matrix.os }}
    name: Node Tests

    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]
        os: [sfdc-hk-ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
      - name: Enable Corepack
        run: corepack enable
      - run: pnpm install --frozen-lockfile
      - run: pnpm test
