name: Node CI Suite

on: push

jobs:
  test:
    runs-on: ${{ matrix.os }}
    name: Node Tests

    strategy:
      matrix:
        node-version: [22.x]
        os: [pub-hk-ubuntu-22.04-small]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test