name: Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Type of release to create'
        required: true
        default: 'beta'
        type: choice
        options:
          - beta
          - stable
      dry_run:
        description: 'Perform a dry run (no actual publishing)'
        required: false
        default: false
        type: boolean

jobs:
  release-please:
    runs-on: pub-hk-ubuntu-24.04-ip
    permissions:
      contents: write
      pull-requests: write
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

  publish:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    runs-on: pub-hk-ubuntu-24.04-ip
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: pnpm install

      - name: Build package
        run: pnpm run build

      - name: Run tests
        run: pnpm test

      - name: Publish to npm
        run: |
          if [ "${{ github.event.inputs.dry_run }}" = "true" ]; then
            echo "DRY RUN: Validating publish process..."
            if [ "${{ github.event.inputs.release_type }}" = "stable" ]; then
              pnpm publish --dry-run --provenance --no-git-checks
            else
              pnpm publish --dry-run --tag beta --provenance --no-git-checks
            fi
          else
            if [ "${{ github.event.inputs.release_type }}" = "stable" ]; then
              pnpm publish --provenance --no-git-checks
            else
              pnpm publish --tag beta --provenance --no-git-checks
            fi
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
